import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';

type Language = 'en' | 'fr';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations = {
  en: {
    // Auth & Generic
    'access_system': 'INIT: Access System',
    'register_subject': 'EXEC: Register Subject',
    'full_name': 'FULL_NAME',
    'email_uplink': 'EMAIL_UPLINK',
    'passkey_secret': 'PASSKEY_SECRET',
    'passkey_hash': 'PASSKEY_HASH',
    'subject_id': 'SUBJECT_ID',
    'system_access': 'SYSTEM ACCESS',
    'auth_required': 'AUTHENTICATION PROTOCOL REQUIRED',
    'enrolling': 'INITIALIZING IDENTITY PARAMETERS',
    'enrollment': 'SUBJECT ENROLLMENT',
    'login_prompt': 'ALREADY ENROLLED? LOGIN',
    'register_prompt': 'EXEC: Create Identity',
    'initializing': 'INITIALIZING...',
    'securing_connection': 'SECURING CONNECTION...',
    'awaiting_input': 'AWAITING INPUT...',
    'language_selector_or': 'OR',
    
    // Quiz
    'evaluation_protocol': 'AI EVALUATION PROTOCOL',
    'integrating': 'INTEGRATING',
    'time_expired': 'TIME_EXPIRED',
    'time_remaining': 's',
    'preparing_export': 'PREPARING EXPORT...',
    'download_cert': 'DOWNLOAD CERTIFICATE (HTML)',
    'finalizing_quiz': 'FINALIZING PROTOCOL...',

    // HUD & Navigation
    'dashboard': 'DASHBOARD',
    'timeline': 'TIMELINE',
    'leaderboard': 'LEADERBOARD',
    'system_logs': 'SYSTEM LOGS',
    'uplink_status': 'UPLINK_STATUS: STABLE',
    'active_session': 'SESSION: ACTIVE',
    'tactical_feed': 'Tactical Feed',
    'mission': 'MISSION',
    'sequence_desc': 'CHRONOLOGICAL DEPLOYMENT SEQUENCE FOR APRIL 26.',
    'system_time': 'SYSTEM_TIME',
    'sync_status': 'SYNC_STATUS',
    'optimal': 'OPTIMAL',
    'end_of_sequence': 'END_OF_SEQUENCE',
    'trans_terminated': 'Transmission Terminated // Log Closed',
    'stream_status': 'Stream Status',
    'temporal_sync': 'Temporal Sync',
    'event_node': 'Event Node',
    'sequence_id': 'Sequence ID',
    'operational': 'Operational',
    'subject_file_nav': 'SUBJECT FILE',
    'data_node_nav': 'DATA NODE',
    'scanner_nav': 'SCANNER',
    'core_nav': 'CORE',
    'sys_status': 'SYSTEM STATUS: ACTIVE',
    'detroit_core': 'DETROIT: CORE',
    'active': 'ACTIVE',
    'subject_identified': 'Subject_Identified',
    'syncing': 'SYNCING...',
    'loading': 'LOADING',
    'encrypted_active': 'ENCRYPTED_LINK_ACTIVE',
    'mission_briefing': 'MISSION BRIEFING',
    'target_date': 'Target Date',
    'deployment': 'Deployment',
    'sector_node': 'Sector Node',
    'activation_fee': 'Activation Fee',
    'dt': 'DT',
    'mission_manifest': 'Mission Manifest',
    'buffet_included': 'Buffet Included',
    'certified': 'CERTIFIED',
    'countdown': 'Deployment Countdown',
    'days': 'Days',
    'hours': 'Hours',
    'mins': 'Mins',
    'mission_node': 'Mission Node',
    'scan_map': 'Scan Map',
    'authorized': 'AUTHORIZED',
    'mission_broadcast': 'MISSION BROADCAST',
    'live_status': 'LIVE_STATUS',
    'nominal': 'NOMINAL',
    'terminate_session': 'Terminate Authorized Session',
    'genai_title': 'GenAI Protocol',
    'genai_desc': 'CORE_LEARNING: Large Language Models, Generative Architectures & Neural Synergy.',
    'workshop_title': 'Applicative Workshop',
    'workshop_desc': 'PRACTICAL_INTEGRATION: Building real-world AI entities & interface deployment.',
    'broadcast_msg': '"All systems calibrated for 26th April. Prepare for GenAI protocol initialization at ISIMS."',
    'broadcast_log': 'SYSTEM_LOG :: ALPHA_1',
    'broadcast_minor': '"Minor fluctuation in sector 7 power routing. Compensating automatically."',
    'ago': 'ago',
    'global_rank': 'GLOBAL EVALUATION RANKING',
    'total_entities': 'TOTAL ENTITIES',
    'network_load': 'NETWORK LOAD',
    'stability_secure': 'STABILITY SECURE',
    'evaluation_secure': 'EVALUATION SECURE',
    'success_rate': 'SUCCESS RATE',
    'eval_completion': 'EVALUATION COMPLETION',
    'apex_entity': 'APEX ENTITY',
    'live_stream': 'LIVE DATA STREAM',
    'auto_refresh': 'AUTO-REFRESH',
    'rank_col': 'RANK',
    'entity_id_col': 'ENTITY ID',
    'designation_col': 'DESIGNATION',
    'eval_pct_col': 'EVAL %',
    'subject_pending': 'SUBJECT_PENDING',
    'system_debrief': 'SYSTEM DEBRIEF',
    'post_op_analysis': 'POST-OPERATION ANALYSIS & FEEDBACK PROTOCOL',
    'log_transmitted': 'LOG TRANSMITTED',
    'thank_you_evolve': 'Thank you for evolving the system.',
    'satisfaction_level': 'Satisfaction Level',
    'critical_failure': 'Critical Failure',
    'efficiency_metric': 'EFFICIENCY METRIC',
    'recorded': 'RECORDED',
    'operator_notes': 'Operator Notes',
    'manual_obs_placeholder': '> Enter manual observation logs...',
    'transmit_log': 'TRANSMIT LOG',
    'syncing_protocols': 'SYNCING EVENT PROTOCOLS...',
    'init_gen_ai': 'INITIALIZING GEN-AI CORE...',
    'establish_uplink': 'ESTABLISHING ISIMS UPLINK...',
    'loading_manifest': 'LOADING EVENT MANIFEST...',
    'config_modules': 'CONFIGURING WORKSHOP MODULES...',
    'protocol_ready': 'DETROIT PROTOCOL READY',
    'become': 'BECOME',
    'ai_conference': 'AI Development Conference',
    'learn_ai': 'Learn AI • Shape Tomorrow',
    'unlock_power': 'Unlock The Power Of Artificial Intelligence',
    'syst_date': 'SYST_DATE',
    'uplink_time': 'UPLINK_TIME',
    'not_evaluated': 'You are not being evaluated...',
    'you_are_evolving': 'You are evolving.',
    'hidden_designation': 'Hidden Designation Unlocked',
    'the_architect': 'THE ARCHITECT',
    'deep_layer_access': 'Access granted to deep-layer protocols. Your interaction patterns deviate from baseline norms. Proceed with caution.',
  },
  fr: {
    // Auth & Generic
    'access_system': 'INIT: Accéder au Système',
    'register_subject': 'EXEC: Enregistrer le Sujet',
    'full_name': 'NOM_COMPLET',
    'email_uplink': 'LIAISON_EMAIL',
    'passkey_secret': 'SECRET_PASSKEY',
    'passkey_hash': 'HASH_PASSKEY',
    'subject_id': 'ID_SUJET',
    'system_access': 'ACCÈS SYSTÈME',
    'auth_required': 'PROTOCOLE D\'AUTHENTIFICATION REQUIS',
    'enrolling': 'INITIALISATION DES PARAMÈTRES D\'IDENTITÉ',
    'enrollment': 'ENRÔLEMENT DU SUJET',
    'login_prompt': 'DÉJÀ ENRÔLÉ ? CONNEXION',
    'register_prompt': 'EXEC: Créer l\'Identité',
    'initializing': 'INITIALISATION...',
    'securing_connection': 'SÉCURISATION DE LA CONNEXION...',
    'awaiting_input': 'EN ATTENTE D\'ENTRÉE...',
    'language_selector_or': 'OU',
    
    // Quiz
    'evaluation_protocol': 'PROTOCOLE D\'ÉVALUATION IA',
    'integrating': 'INTÉGRATION',
    'time_expired': 'TEMPS_ÉCOULÉ',
    'time_remaining': 's',
    'preparing_export': 'PRÉPARATION DE L\'EXPORT...',
    'download_cert': 'TÉLÉCHARGER LE CERTIFICAT (HTML)',
    'finalizing_quiz': 'FINALISATION DU PROTOCOLE...',

    // HUD & Navigation
    'dashboard': 'TABLEAU DE BORD',
    'timeline': 'CHRONOLOGIE',
    'leaderboard': 'CLASSEMENT',
    'system_logs': 'JOURNAUX SYSTÈME',
    'uplink_status': 'STATUT_LIAISON: STABLE',
    'active_session': 'SESSION: ACTIVE',
    'tactical_feed': 'Flux Tactique',
    'mission': 'MISSION',
    'sequence_desc': 'SÉQUENCE DE DÉPLOIEMENT CHRONOLOGIQUE POUR LE 26 AVRIL.',
    'system_time': 'TEMPS_SYSTÈME',
    'sync_status': 'STATUT_SYNC',
    'optimal': 'OPTIMAL',
    'end_of_sequence': 'FIN_DE_SÉQUENCE',
    'trans_terminated': 'Transmission Terminée // Journal Clos',
    'stream_status': 'Statut du Flux',
    'temporal_sync': 'Sync Temporelle',
    'event_node': 'Nœud d\'Événement',
    'sequence_id': 'ID de Séquence',
    'operational': 'Opérationnel',
    'subject_file_nav': 'DOSSIER SUJET',
    'data_node_nav': 'NŒUD DONNÉES',
    'scanner_nav': 'SCANNER',
    'core_nav': 'CŒUR',
    'sys_status': 'STATUT SYSTÈME: ACTIF',
    'detroit_core': 'DETROIT: CŒUR',
    'active': 'ACTIF',
    'subject_identified': 'Sujet_Identifié',
    'syncing': 'SYNCHRONISATION...',
    'loading': 'CHARGEMENT',
    'encrypted_active': 'LIEN_CHIFFRÉ_ACTIF',
    'mission_briefing': 'BRIEFING DE MISSION',
    'target_date': 'Date Cible',
    'deployment': 'Déploiement',
    'sector_node': 'Nœud de Secteur',
    'activation_fee': 'Frais d\'Activation',
    'dt': 'DT',
    'mission_manifest': 'Manifeste de Mission',
    'buffet_included': 'Buffet Inclus',
    'certified': 'CERTIFIÉ',
    'countdown': 'Compte à Rebours',
    'days': 'Jours',
    'hours': 'Heures',
    'mins': 'Mins',
    'mission_node': 'Nœud de Mission',
    'scan_map': 'Scanner Carte',
    'authorized': 'AUTORISÉ',
    'mission_broadcast': 'DIFFUSION MISSION',
    'live_status': 'STATUT_DIRECT',
    'nominal': 'NOMINAL',
    'terminate_session': 'Terminer la Session Autorisée',
    'genai_title': 'Protocole Gen-IA',
    'genai_desc': 'APPRENTISSAGE_CENTRAL : Grands Modèles de Langage, Architectures Génératives et Synergie Neurale.',
    'workshop_title': 'Atelier Applicatif',
    'workshop_desc': 'INTÉGRATION_PRATIQUE : Créer des entités IA réelles et déploiement d\'interface.',
    'broadcast_msg': '"Tous les systèmes sont calibrés pour le 26 avril. Préparez-vous pour l\'initialisation du protocole Gen-IA à l\'ISIMS."',
    'broadcast_log': 'JOURNAL_SYSTÈME :: ALPHA_1',
    'broadcast_minor': '"Fluctuation mineure dans le routage d\'énergie du secteur 7. Compensation automatique."',
    'ago': 'il y a',
    'global_rank': 'CLASSEMENT MONDIAL',
    'total_entities': 'TOTAL DES ENTITÉS',
    'network_load': 'CHARGE RÉSEAU',
    'stability_secure': 'STABILITÉ SÉCURISÉE',
    'evaluation_secure': 'ÉVALUATION SÉCURISÉE',
    'success_rate': 'TAUX DE RÉUSSITE',
    'eval_completion': 'COMPLÉTION ÉVALUATION',
    'apex_entity': 'ENTITÉ APEX',
    'live_stream': 'FLUX DE DONNÉES EN DIRECT',
    'auto_refresh': 'AUTO-ACTUALISATION',
    'rank_col': 'RANG',
    'entity_id_col': 'ID ENTITÉ',
    'designation_col': 'DÉSIGNATION',
    'eval_pct_col': 'ÉVAL %',
    'subject_pending': 'SUJET_EN_ATTENTE',
    'system_debrief': 'BILAN DU SYSTÈME',
    'post_op_analysis': 'ANALYSE POST-OPÉRATIONNELLE & PROTOCOLE DE RETOUR',
    'log_transmitted': 'JOURNAL TRANSMIS',
    'thank_you_evolve': 'Merci de faire évoluer le système.',
    'satisfaction_level': 'Niveau de Satisfaction',
    'critical_failure': 'Échec Critique',
    'efficiency_metric': 'MÉTRIQUE D\'EFFICACITÉ',
    'recorded': 'ENREGISTRÉE',
    'operator_notes': 'Notes de l\'Opérateur',
    'manual_obs_placeholder': '> Entrez les journaux d\'observation manuels...',
    'transmit_log': 'TRANSMETTRE LE JOURNAL',
    'syncing_protocols': 'SYNCHRONISATION DES PROTOCOLES...',
    'init_gen_ai': 'INITIALISATION DU CŒUR IA...',
    'establish_uplink': 'ÉTABLISSEMENT DE LA LIAISON ISIMS...',
    'loading_manifest': 'CHARGEMENT DU MANIFESTE...',
    'config_modules': 'CONFIGURATION DES MODULES...',
    'protocol_ready': 'PROTOCOLE DETROIT PRÊT',
    'become': 'DEVENIR',
    'ai_conference': 'Conférence sur le Développement de l\'IA',
    'learn_ai': 'Apprendre l\'IA • Façonner Demain',
    'unlock_power': 'Libérez le Pouvoir de l\'Intelligence Artificielle',
    'syst_date': 'DATE_syst',
    'uplink_time': 'HEURE_LIAISON',
    'not_evaluated': 'Vous n\'êtes pas en cours d\'évaluation...',
    'you_are_evolving': 'Vous évoluez.',
    'hidden_designation': 'Désignation Cachée Déverrouillée',
    'the_architect': 'L\'ARCHITECTE',
    'deep_layer_access': 'Accès accordé aux protocoles de couche profonde. Vos modèles d\'interaction dévient des normes de base. Procéder avec prudence.',
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem('epik_language');
    return (saved as Language) || 'en';
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('epik_language', lang);
  };

  const t = (key: string): string => {
    return (translations[language] as any)[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
